import pytest
import base64
import re
import sympy

# Import the Mathematica Backend (which we just fixed)
from ides.mathematica.kernel.engine import MathematicaBackend

# Try to import the Mathex Plotly Backend (adjust path if necessary)
try:
    from shared.plotting_engine.plotly_backend import generate_plot_html 
    HAS_MATHEX_PLOTLY = True
except ImportError:
    HAS_MATHEX_PLOTLY = False

# The strict limit for QWebEngineView data URIs is ~2MB (2,097,152 bytes)
# We set our test limit much lower (500KB) to ensure high performance and zero lag.
MAX_SAFE_PAYLOAD_SIZE = 500 * 1024 


@pytest.fixture
def math_backend():
    """Fixture to provide a loaded Mathematica Engine."""
    backend = MathematicaBackend()
    backend._ensure_loaded()
    return backend


def test_mathematica_3d_plot_size_and_cdn(math_backend):
        """
        Test 1: Ensures that 3D plots generated by Mathematica Engine
        do not exceed WebEngine IPC limits and properly deploy locally for offline access.
        """
        import sympy
        x, y = sympy.symbols('x y')

        # Generate a complex 3D surface
        result = math_backend._plot3d_wrapper(sympy.sin(x) * sympy.cos(y), (x, -5, 5), (y, -5, 5))

        # 1. ASSERT NO MASSIVE BASE64 HTML STRING
        # If the plot is injected directly via Base64, it crashes the WebEngine console IPC.
        assert "base64" not in result.html, \
            "CRITICAL: Base64 payload detected. This exceeds WebEngine IPC limits."

        # 2. ASSERT OFFLINE PHYSICAL FILE DEPLOYMENT
        # The plot must be written to a temp file and mirrored with Plotly JS to bypass strict CORS.
        assert "file:" in result.html, \
            "Plot iframe must use a physical file:// URI to load the local Plotly script offline."
        assert "math3d_" in result.html, \
            "Plot iframe should point to the securely generated temp file."

def test_matplotlib_2d_payload_size(math_backend):
    """
    Test 3: Ensures standard 2D plots (Matplotlib) are rendering efficiently 
    and aren't accidentally ballooning in size.
    """
    x = sympy.symbols('x')
    
    # Generate a standard 2D plot
    result = math_backend._plot_wrapper(sympy.sin(x), (x, -10, 10))
    
    # Matplotlib outputs an image src rather than an iframe
    match = re.search(r"base64,([^']+)'", result.html)
    assert match is not None, "Could not find the Base64 image data in the 2D output."
    
    b64_data = match.group(1)
    
    # 2D Plots should be heavily compressed PNGs, usually around 20-40KB
    assert len(b64_data) < 200 * 1024, \
        f"2D Plot PNG data is unusually large ({len(b64_data) / 1024:.2f} KB). Check DPI settings."