import pytest
import base64
import re
import sympy

# Import the Mathematica Backend (which we just fixed)
from ides.mathematica.kernel.engine import MathematicaBackend

# Try to import the Mathex Plotly Backend (adjust path if necessary)
try:
    from shared.plotting_engine.plotly_backend import generate_plot_html 
    HAS_MATHEX_PLOTLY = True
except ImportError:
    HAS_MATHEX_PLOTLY = False

# The strict limit for QWebEngineView data URIs is ~2MB (2,097,152 bytes)
# We set our test limit much lower (500KB) to ensure high performance and zero lag.
MAX_SAFE_PAYLOAD_SIZE = 500 * 1024 


@pytest.fixture
def math_backend():
    """Fixture to provide a loaded Mathematica Engine."""
    backend = MathematicaBackend()
    backend._ensure_loaded()
    return backend


def test_mathematica_3d_plot_size_and_cdn(math_backend):
    """
    Test 1: Ensures that 3D plots generated by Mathematica Engine 
    do not exceed WebEngine limits and properly utilize the Plotly CDN.
    """
    x, y = sympy.symbols('x y')
    
    # Generate a complex 3D surface: sin(x) * cos(y)
    # This is exactly what the user would type in the IDE.
    result = math_backend._plot3d_wrapper(sympy.sin(x) * sympy.cos(y), (x, -5, 5), (y, -5, 5))
    
    # 1. Extract the Base64 string from the generated iframe HTML
    match = re.search(r"base64,([^']+)'", result.html)
    assert match is not None, "Could not find the Base64 data URI in the HTML output."
    
    b64_data = match.group(1)
    raw_html = base64.b64decode(b64_data).decode('utf-8')
    
    payload_size = len(b64_data)
    
    # 2. ASSERT PAYLOAD SIZE:
    # If include_plotlyjs=True, this will be > 4MB and crash the UI.
    # If include_plotlyjs='cdn', this will be ~50KB.
    assert payload_size < MAX_SAFE_PAYLOAD_SIZE, \
        f"CRITICAL: 3D Plot payload is too large ({payload_size / 1024:.2f} KB). " \
        f"It exceeds the 2MB WebEngine limit. Ensure include_plotlyjs='cdn' is used."

    # 3. ASSERT CDN INCLUSION:
    # Verify that the lightweight CDN script is actually in the HTML, 
    # otherwise the plot will be a blank white box.
    assert "cdn.plot.ly" in raw_html, \
        "Plotly CDN script tag missing from HTML! The 3D plot will render completely blank."


@pytest.mark.skipif(not HAS_MATHEX_PLOTLY, reason="Mathex Plotly Backend not found")
def test_mathex_plotly_backend_size():
    """
    Test 2: Ensure the shared Mathex Plotly backend respects the same rules.
    """
    import plotly.graph_objects as go
    import numpy as np
    
    # Create a dense dataset to stress-test the payload size
    x = np.linspace(-5, 5, 100)
    y = np.linspace(-5, 5, 100)
    X, Y = np.meshgrid(x, y)
    Z = np.sin(X) * np.cos(Y)
    
    fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y)])
    
    # Simulate your backend generating the HTML
    # (Adjust this call to match your exact shared PlotEngine architecture)
    raw_html = fig.to_html(full_html=True, include_plotlyjs='cdn')
    b64_data = base64.b64encode(raw_html.encode('utf-8')).decode('utf-8')
    
    payload_size = len(b64_data)
    
    assert payload_size < MAX_SAFE_PAYLOAD_SIZE, \
        f"Mathex 3D Plot payload is too large ({payload_size / 1024:.2f} KB). " \
        f"It exceeds the safe WebEngine limit."

    assert "cdn.plot.ly" in raw_html, "Mathex Plotly CDN script missing!"


def test_matplotlib_2d_payload_size(math_backend):
    """
    Test 3: Ensures standard 2D plots (Matplotlib) are rendering efficiently 
    and aren't accidentally ballooning in size.
    """
    x = sympy.symbols('x')
    
    # Generate a standard 2D plot
    result = math_backend._plot_wrapper(sympy.sin(x), (x, -10, 10))
    
    # Matplotlib outputs an image src rather than an iframe
    match = re.search(r"base64,([^']+)'", result.html)
    assert match is not None, "Could not find the Base64 image data in the 2D output."
    
    b64_data = match.group(1)
    
    # 2D Plots should be heavily compressed PNGs, usually around 20-40KB
    assert len(b64_data) < 200 * 1024, \
        f"2D Plot PNG data is unusually large ({len(b64_data) / 1024:.2f} KB). Check DPI settings."